working with APP_ENV flag
department-of-veterans-affairs/next-build pull request #176
Opened 2023-09-22 17:02 UTC by jtmst

## Description
Relates to #[14977](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14977). (or closes?)

## Testing done
Local testing with mock env files

## Screenshots
<img width="1212" alt="Screen Shot 2023-09-22 at 12 13 10 PM" src="https://github.com/department-of-veterans-affairs/next-build/assets/61624970/634cad1e-28bf-4bd1-b30a-7255b4b31090">
<img width="1212" alt="Screen Shot 2023-09-22 at 12 15 43 PM" src="https://github.com/department-of-veterans-affairs/next-build/assets/61624970/268299f0-4fb4-4ea3-bd1b-4e69bc3f0055">

## QA steps
- Run `yarn dev`
  - Verify in network tab that static-entry files are coming from the local generated files
- Create a .env.staging file with a value of  NEXT_PUBLIC_ASSETS_URL=https://s3-us-gov-west-1.amazonaws.com/content.staging.va.gov/generated/ 
  - run `APP_ENV=staging yarn dev'
  - verify in network tab that static-entry files are coming from the appropriate staging bucket

Note:
- This adds the capability to call on different env files with the APP_ENV flag, but still will require that those env files are created in their appropriate environments

## Is this PR blocked by another PR?
- Add the `DO NOT MERGE` label
- Add links to additional PRs here:

2023-09-22 22:45 UTC, tjheffner requested changes
Per https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables next supports and has special handling for `.env.local`, `.env.development`, `.env.production` and `.env.test` in the root directory out of the box... I am not opposed to not using the root level and moving them to `./envs/`, and your changes seem to pick up the exposed `NEXT_PUBLIC_` variables, but please double check about `.env.test` and its location.


the changes to yarn.lock again seem huge for what is ultimately being added

2023-09-22 22:45 UTC, tjheffner commented on .eslintrc.json
> +    },
per slack thread with the 3 of us, this can be removed

2023-09-22 22:45 UTC, tjheffner commented on README.md
> +The APP_ENV flag can be used to designate which .env file you want to use. Ensure you're env files are in ./env, and then run your build or dev command with a leading APP_ENV=local.
I see you moved `.env.example` but not `.env.test`, just curious if `.env.test` gets picked up when it lives in this folder? We preface a bunch of package.json's `test:` scripts with `NODE_ENV=test`

2023-09-25 12:59 UTC, jtmst commented
> Per https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables next supports and has special handling for `.env.local`, `.env.development`, `.env.production` and `.env.test` in the root directory out of the box... I am not opposed to not using the root level and moving them to `./envs/`, and your changes seem to pick up the exposed `NEXT_PUBLIC_` variables, but please double check about `.env.test` and its location.
> 
> the changes to yarn.lock again seem huge for what is ultimately being added

I'll adjust for the test environments and push that up.  

Nexts built in env support forces you to use the local env file when running `yarn dev`, and requires some extra set up to support envs besides those listed (staging).  I think this is the approach we want, once i fix this for test.

2023-09-25 15:33 UTC, tjheffner approved these changes

2023-09-25 15:34 UTC, merged